// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package chunk

import (
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PebbleChunkModel) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			err = dc.ReadExactBytes((z.ID)[:])
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "writer_key":
			z.WriterKey, err = dc.ReadBytes(z.WriterKey)
			if err != nil {
				err = msgp.WrapError(err, "WriterKey")
				return
			}
		case "state":
			z.State, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "State")
				return
			}
		case "size":
			z.Size, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "version":
			z.Version, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "created_at":
			z.CreatedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "updated_at":
			z.UpdatedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "deleted_at":
			z.DeletedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "DeletedAt")
				return
			}
		case "expires_at":
			z.ExpiresAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PebbleChunkModel) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	_ = zb0001Mask
	if z.Size == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Version == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.CreatedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.UpdatedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.DeletedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.ExpiresAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "id"
		err = en.Append(0xa2, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteBytes((z.ID)[:])
		if err != nil {
			err = msgp.WrapError(err, "ID")
			return
		}
		// write "writer_key"
		err = en.Append(0xaa, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.WriterKey)
		if err != nil {
			err = msgp.WrapError(err, "WriterKey")
			return
		}
		// write "state"
		err = en.Append(0xa5, 0x73, 0x74, 0x61, 0x74, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.State)
		if err != nil {
			err = msgp.WrapError(err, "State")
			return
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "size"
			err = en.Append(0xa4, 0x73, 0x69, 0x7a, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Size)
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "version"
			err = en.Append(0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.Version)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "created_at"
			err = en.Append(0xaa, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteTime(z.CreatedAt)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "updated_at"
			err = en.Append(0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteTime(z.UpdatedAt)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "deleted_at"
			err = en.Append(0xaa, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteTime(z.DeletedAt)
			if err != nil {
				err = msgp.WrapError(err, "DeletedAt")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "expires_at"
			err = en.Append(0xaa, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteTime(z.ExpiresAt)
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PebbleChunkModel) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	_ = zb0001Mask
	if z.Size == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Version == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.CreatedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.UpdatedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.DeletedAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.ExpiresAt == (time.Time{}) {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "id"
		o = append(o, 0xa2, 0x69, 0x64)
		o = msgp.AppendBytes(o, (z.ID)[:])
		// string "writer_key"
		o = append(o, 0xaa, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79)
		o = msgp.AppendBytes(o, z.WriterKey)
		// string "state"
		o = append(o, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x65)
		o = msgp.AppendString(o, z.State)
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "size"
			o = append(o, 0xa4, 0x73, 0x69, 0x7a, 0x65)
			o = msgp.AppendInt64(o, z.Size)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "version"
			o = append(o, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
			o = msgp.AppendUint64(o, z.Version)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "created_at"
			o = append(o, 0xaa, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			o = msgp.AppendTime(o, z.CreatedAt)
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "updated_at"
			o = append(o, 0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			o = msgp.AppendTime(o, z.UpdatedAt)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "deleted_at"
			o = append(o, 0xaa, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
			o = msgp.AppendTime(o, z.DeletedAt)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "expires_at"
			o = append(o, 0xaa, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74)
			o = msgp.AppendTime(o, z.ExpiresAt)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PebbleChunkModel) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			bts, err = msgp.ReadExactBytes(bts, (z.ID)[:])
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "writer_key":
			z.WriterKey, bts, err = msgp.ReadBytesBytes(bts, z.WriterKey)
			if err != nil {
				err = msgp.WrapError(err, "WriterKey")
				return
			}
		case "state":
			z.State, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "State")
				return
			}
		case "size":
			z.Size, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "version":
			z.Version, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "created_at":
			z.CreatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "updated_at":
			z.UpdatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "deleted_at":
			z.DeletedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DeletedAt")
				return
			}
		case "expires_at":
			z.ExpiresAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PebbleChunkModel) Msgsize() (s int) {
	s = 1 + 3 + msgp.ArrayHeaderSize + (16 * (msgp.ByteSize)) + 11 + msgp.BytesPrefixSize + len(z.WriterKey) + 6 + msgp.StringPrefixSize + len(z.State) + 5 + msgp.Int64Size + 8 + msgp.Uint64Size + 11 + msgp.TimeSize + 11 + msgp.TimeSize + 11 + msgp.TimeSize + 11 + msgp.TimeSize
	return
}
